apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-lab-stage
  namespace: argocd
spec:
  project: demo-project
  source:
    repoURL: https://github.com/maliniak/lab.git
    targetRevision: main
    path: k8s/base
    helm:
      releaseName: demo-lab-stage
      valueFiles:
        - values-stage.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: demo-stage
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
