backendOrders:
  replicaCount: 1
  image:
    repository: 437952802873.dkr.ecr.eu-central-1.amazonaws.com/gitops-lab/backend-orders
    tag: c53dc66e4d499492c8509397d56cd635c17dd8e2
    pullPolicy: Always
  service:
    port: 8000
  resources:
    requests:
      cpu: 250m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

backendProducts:
  replicaCount: 1
  image:
    repository: 437952802873.dkr.ecr.eu-central-1.amazonaws.com/gitops-lab/backend-products
    tag: c53dc66e4d499492c8509397d56cd635c17dd8e2
    pullPolicy: Always
  service:
    port: 8000
  resources:
    requests:
      cpu: 250m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

frontend:
  replicaCount: 1
  image:
    repository: 437952802873.dkr.ecr.eu-central-1.amazonaws.com/gitops-lab/frontend
    tag: c53dc66e4d499492c8509397d56cd635c17dd8e2
    pullPolicy: Always
  service:
    port: 80
    targetPort: 8000
  publicApiBasePath: /api
  resources:
    requests:
      cpu: 250m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

ingress:
  enabled: true
  className: alb
  scheme: internet-facing
  targetType: ip
  healthcheckPath: /health
